version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "2221:3000"
    env_file:
      - .env  
    networks:
      - testnet

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    command: ["npx", "playwright", "test"]
    networks:
      - testnet
    ipc: host

networks:
  testnet:
