name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo "Start the shopping store application"
          echo "Install dependencies from lockfile"
          echo "Run playwright tests"

           






